[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Aakash Shah <aashah@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"

[[bin]]
name = "day1"
path = "src/day1.rs"

